### ISSUE TITLE
Dependency Version Conflict Due to web Package Incompatibility

### ISSUE THREAD

**Issue by NaderMohamedMusa** [ALI-tech-tech/jh_services#1]
A version conflict occurs due to different dependencies requiring incompatible versions of the web package. One dependency requires web ^1.0.0, while another depends on web ^0.5.1. As no available version satisfies both requirements, the version-solving process fails, preventing successful package resolution.

**Comment by ALI-tech-tech** [comment]
I understand the version conflict issue you're facing with the web package, and I truly appreciate you bringing this to my attention. It seems that one dependency in your project requires web ^1.0.0, while another depends on web ^0.5.1, which is leading to this version-solving problem. Since no single version can satisfy both, the resolution process fails, preventing the project from moving forward.

I'm genuinely interested in working through this issue with you to find a solution. We could either look into upgrading or downgrading some dependencies, or possibly find alternatives that maintain compatibility. Let me know how you'd like to proceed!

**Comment by ALI-tech-tech** [comment]
I completely understand the version conflict you're facing with the web package, and I appreciate you bringing this issue to my attention. It seems that one dependency requires web ^1.0.0, while another depends on web ^0.5.1, which is causing the conflict and preventing dependency resolution. Since no single version can satisfy both requirements, the process fails, affecting the project.

I'm very interested in resolving this issue with you, whether by upgrading or downgrading some dependencies or finding compatible alternatives. Let me know how you'd like to proceed!

**Comment by ALI-tech-tech** [comment]
Thank you for raising the issue and helping us improve the package. We have reviewed the issue and resolved it in the latest update. Please check your project and confirm that everything is working as expected now.

If you have any further questions or feedback, feel free to reach out. We're here to support you!
